name: Bug Report
description: Report a bug to help us improve
title: '[BUG]: '
labels: ['bug', 'triage']

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug.

        Please fill in as much of the template below as you're able.

        ---
  - type: input
    id: contact
    attributes:
      label: Contact
      description: ow can we get in touch with you if we need more info?
      placeholder: email@example.com
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Describe what you expected to happen
    validations:
      required: true
  - type: dropdown
    id: os-environment
    attributes:
      label: OS Environment
      multiple: true
      description: What OS are you using?
      options:
        - Windows
        - macOS
        - Linux
        - Other
    validations:
      required: true
  - type: input
    id: vscode-version
    attributes:
      label: VS Code Version
      description: What version of VS Code are you using?
      placeholder: 1.52.1
    validations:
      required: true
  - type: input
    id: extension-version
    attributes:
      label: Extension Version
      description: What version of the extension are you using?
      placeholder: 1.0.0
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Add any other context about the problem here.
      placeholder: |
        - Screenshots
        - Stack traces
        - Related issues
        - Suggestions on how to fix
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes: Code of Conduct
    description: |
      By submitting this issue, you agree to abide by our [Code of Conduct](https://github.com/shahafashash/coffee-patterns/CODE_OF_CONDUCT.md).
      Violations of this code may result in your access to this project being
      restricted or removed.
    options:
      - label: I agree to follow this project's Code of Conduct
        required: true


