name: Feature Request
description: Suggest an idea for this project
title: '[FEATURE REQUEST]: '
labels: ['feature', 'triage']

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature!

        Please fill in as much of the template below as you're able.

        ---

  - type: input
    id: contact
    attributes:
      label: Contact
      description: How can we get in touch with you if we need more info?
      placeholder: email@example.com
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of the new feature you are proposing.
      placeholder: Describe the feature
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Explain why you believe this feature would be beneficial to the project.
      placeholder: Why do you think this feature is important?
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: Any ideas on how this feature could be implemented?
      placeholder: Share your thoughts on the implementation
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any additional information, links, or screenshots you'd like to share?
      placeholder: Share any additional information
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: |
        By submitting this request, you agree to abide by our [Code of Conduct](https://github.com/shahafashash/coffee-patterns/blob/main/CODE_OF_CONDUCT.md).
        Violations of this code may result in your access to this project being restricted or removed.
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
