name: Version

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

jobs:
    version:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                    ref: ${{ github.head_ref }}
                    fetch-depth: 0

            - name: Version
              id: version
              uses: codacy/git-version@2.7.1

            - name: Check version
              run: |
                  echo "Version: ${{ steps.version.outputs.version }}"
