name: Version

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

jobs:
    version:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                    ref: ${{ github.head_ref }}
                    fetch-depth: 0

            - name: Git Version
              id: version
              uses: codacy/git-version@2.7.1

            - name: Check version
              run: |
                echo "Previous version: ${{ steps.version.outputs.previous-version }}"
                echo "New version: ${{ steps.version.outputs.version }}"

            - name: Commit version
              if: ${{ steps.version.outputs.version != steps.version.outputs.previous-version }}
              run: |
                git config --global user.name "shahafashash"
                git config --global user.email "shahaf.ashash@icloud.com"
                git tag ${{ steps.version.outputs.version }}
                git push origin ${{ steps.version.outputs.version }} --tags



